// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Title     string
	Year      int32
	Runtime   int32
	Genres    []string
	Version   int32
}

type Token struct {
	Hash   []byte
	UserID int64
	Expiry pgtype.Timestamptz
	Scope  string
}

type User struct {
	ID           int64
	CreatedAt    pgtype.Timestamptz
	Name         string
	Email        string
	PasswordHash []byte
	Activated    bool
	Version      int32
}
