// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	Title     string
	Year      int32
	Runtime   int32
	Genres    []string
	Version   int32
}
