// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (hash, user_id, expiry, scope)
VALUES ($1, $2, $3, $4)
`

type CreateTokenParams struct {
	Hash   []byte
	UserID int64
	Expiry pgtype.Timestamptz
	Scope  string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.Exec(ctx, createToken,
		arg.Hash,
		arg.UserID,
		arg.Expiry,
		arg.Scope,
	)
	return err
}

const deleteAllForUser = `-- name: DeleteAllForUser :exec
DELETE FROM tokens
WHERE scope = $1 AND user_id = $2
`

type DeleteAllForUserParams struct {
	Scope  string
	UserID int64
}

func (q *Queries) DeleteAllForUser(ctx context.Context, arg DeleteAllForUserParams) error {
	_, err := q.db.Exec(ctx, deleteAllForUser, arg.Scope, arg.UserID)
	return err
}
